### ISSUE TITLE
Bruuhh

### ISSUE THREAD

**Issue by W357W00DS** [whiterabb17/MkCheck#1]
Could you please contact. kl33dus @ proton.me

**Comment by whiterabb17** [comment]
may I ask why?

**Comment by W357W00DS** [comment]
But of course. Just needed some help. Wasn't sure how to ask or protocols.
And only if you didn't mind some guidance giving

**Comment by whiterabb17** [comment]
Lulz kay then

**Comment by W357W00DS** [comment]
Had a couple questions wasn't sure how or if you could just message someone

**Comment by whiterabb17** [comment]
you can contact me at s1l3n7h0s7@gmail.com

**Comment by W357W00DS** [comment]
Lmao 🤦 thanks.
